name: mobile_app
description: "ERP Nettoyage Plus - Application Mobile Agent"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Auth
  http: ^1.2.0
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.3.0

  # State management
  provider: ^6.1.0

  # Localisation & formats
  intl: ^0.19.0
  google_fonts: ^6.2.0

  # GPS
  geolocator: ^13.0.0

  # Camera & gallery
  image_picker: ^1.1.0

  # Google Maps
  google_maps_flutter: ^2.9.0

  # Firebase (Push notifications)
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.4

  # Local notifications (affichage des notifs FCM en foreground)
  flutter_local_notifications: ^18.0.1

  # Icônes Material supplémentaires
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
